data:extend({
  {
    type = "bool-setting",
    name = "rvc-enable",
    setting_type = "runtime-per-user",
    default_value = true,
    order = "a-a",
  },
  {
    type = "string-setting",
    name = "rvc-default-preset",
    setting_type = "runtime-per-user",
    default_value = "classic_crt",
    allowed_values = {
      "classic_crt",
      "pipboy",
      "vhs",
      "military",
      "scifi",
      "mono_green",
      "mono_amber",
      "clean",
    },
    order = "a-b",
  },
  {
    type = "bool-setting",
    name = "rvc-remote-view-only",
    setting_type = "runtime-per-user",
    default_value = true,
    order = "a-c",
  },
  {
    type = "double-setting",
    name = "rvc-master-intensity",
    setting_type = "runtime-per-user",
    default_value = 1.0,
    minimum_value = 0.0,
    maximum_value = 1.5,
    order = "a-d",
  },
  {
    type = "bool-setting",
    name = "rvc-debug",
    setting_type = "runtime-per-user",
    default_value = false,
    order = "z-a",
  },
})
